// Article data — shared between News section and article reader page
window.ARTICLES = [
  {
    id: "government-backed-venture",
    category: "Venture Capital",
    title: "Why Government-Backed Venture Is the Smartest Capital on the Table",
    excerpt: "Most founders think of government funding as slow, bureaucratic, and not worth the paperwork. They are wrong. In 30 years of building companies across 4 continents, the single most undervalued tool on the cap table is non-dilutive public capital.",
    date: "April 13, 2026",
    readTime: "5 min read",
    author: "Julien Uhlig",
    authorRole: "Founder, EX Venture",
    image: (window.__resources && window.__resources.art1) || "assets/photos/meeting-01.jpg",
    lead: "Most founders treat government money like a last resort — a paperwork tax for companies that couldn't raise from anyone else. After thirty years of structuring deals across the EU, the US, and emerging markets, I can tell you the opposite is true. The founders who know how to use it move faster, dilute less, and build companies that institutions actually want to back.",
    body: [
      { type: "h2", text: "The myth, and where it comes from" },
      { type: "p", text: "The narrative is familiar: government programs are slow, the forms are byzantine, the reporting requirements eat your time, and the money arrives months after you needed it. Most of this is true on the surface — and almost none of it survives contact with a founder who has done it twice." },
      { type: "p", text: "The reason is simple. The first government grant looks impossible because you are learning the system from zero. The second looks routine. By the third, you have a template, a relationship, and a track record the next program officer can verify in an hour." },
      { type: "h2", text: "What the cap table actually does" },
      { type: "p", text: "Take €2M of non-dilutive public funding into a Series Seed company and you have done something an equity investor cannot do: you have extended the runway without selling a percentage point. That €2M is the equivalent of raising €4–8M at the same valuation — except no one took a board seat, no one diluted the founders, and no one is going to push for a premature exit." },
      { type: "p", text: "When the institutional round arrives, the conversation changes. The cap table shows discipline. The product has months of additional execution time built on top of it. The questions move from \"how will you survive the year?\" to \"how much can we deploy?\"" },
      { type: "h2", text: "Where the money actually lives" },
      { type: "p", text: "Across the programs we've worked with — Horizon Europe, IRA-linked clean-energy grants, BMBF funding lines in Germany, regional development arms in Singapore and Malaysia — the pattern is consistent. The largest pools sit in three categories: applied research clusters, decarbonisation and energy systems, and dual-use infrastructure with public-good components." },
      { type: "p", text: "Deep tech, cleantech, AI infrastructure, and anything touching grid, water, food, or critical materials sits squarely in the funded zones. If your company is in one of those categories, public capital is not a side option. It is the largest non-dilutive lever you have." },
      { type: "h2", text: "The real cost — and how to manage it" },
      { type: "p", text: "There are two costs. The first is time. You will spend weeks structuring an application, often with research partners. The second is reporting — quarterly or annual, depending on the program. Both are real. Neither is fatal." },
      { type: "p", text: "The trick is to write the grant the way you would structure an institutional round: with a clear use of funds, a measurable milestone schedule, and a deliverable cadence you would have committed to anyway. If the grant requires you to do something you would not otherwise do, do not take it. If it pays you to do what you were already planning, the work is essentially free money." },
      { type: "h2", text: "Why investors prefer companies that take it" },
      { type: "p", text: "We have seen this from both sides of the table. As an LP and as an operator, the companies with public funding on the cap table sell a different story: less burn pressure, longer planning horizons, and validation from a body that has no incentive to overstate its conviction. Government programs don't FOMO into deals. When they fund something, they have technical reviewers, market reviewers, and policy reviewers all agreeing the company is worth the public money." },
      { type: "p", text: "That is signal an institutional VC cannot manufacture. And it is one of the reasons our portfolio companies routinely close institutional rounds at higher valuations than peers with comparable revenue but only private capital behind them." },
      { type: "h2", text: "The work, then" },
      { type: "p", text: "If you are building in deep tech or cleantech and you have not mapped the grant landscape in your jurisdiction, you are leaving money on the table. €160M+ has moved across our portfolio in the last decade from these programs. None of it required a board seat. Most of it required a relationship and a willingness to do the work." },
      { type: "p", text: "Do the work. Talk to people who have done it before. Apply more than once. The second time is faster." },
    ],
  },
  {
    id: "operators-discount",
    category: "Operating Thesis",
    title: "The Operator's Discount: Why We Co-Build Instead of Co-Investing",
    excerpt: "The most expensive thing a founder can buy is a passive investor. The least expensive thing on a cap table is an operator who has done this work before and is willing to do it again with you.",
    date: "March 28, 2026",
    readTime: "4 min read",
    author: "Julien Uhlig",
    authorRole: "Founder, EX Venture",
    image: (window.__resources && window.__resources.quoteImg) || "assets/photos/meeting-03.jpg",
    lead: "Most venture capital is structured around a polite fiction: that the money is the help. In our portfolio, the money is the entry fee. The help is the work we do alongside founders, in the room, in the months when nothing is glamorous and everything is hard.",
    body: [
      { type: "h2", text: "What \"fully in\" looks like" },
      { type: "p", text: "Inside our portfolio, the first month of a new investment looks the same every time. We sit down with the founder for two full days. We map the next six months of cash, hiring, customer milestones, and capital partners. We agree on what \"good\" looks like in 90 days and what \"trouble\" looks like at the same horizon. Then we work it." },
      { type: "p", text: "Some weeks that means closing a strategic partner the founder has been chasing for months. Some weeks it means stepping in to negotiate a customer contract, because the founder is in the wrong country to take the meeting. Some weeks it means sitting with a CTO whose first hire is about to quit and figuring out whether to fight to keep them." },
      { type: "h2", text: "Why most venture capital can't do this" },
      { type: "p", text: "It isn't laziness. It is structure. Most funds are designed to make 25–40 investments per partner. The math forces a passive model. A partner with 30 active boards can only deliver capital and introductions. Anything more is a kindness, not a contract." },
      { type: "p", text: "We made a different choice. We hold fewer positions. We engage on a daily cadence with founders for the first 90 days and a weekly cadence after that. The trade-off is obvious: we deploy less, more slowly, into companies where we are confident the work we do matters more than the cheque we write." },
      { type: "h2", text: "The discount, and who pays it" },
      { type: "p", text: "The economic shape of this looks like a discount to founders. We take less ownership at entry than a passive fund of comparable size would, because we know we are going to add real value through the work — and the cap table needs to reflect that. The trade we ask in return is access: we want to be the first call when something is breaking and the first call when something is closing." },
      { type: "p", text: "It is a deal that works for a specific kind of founder. The ones who want a partner who will show up. The ones who do not need to be told that \"value-add\" is mostly a sticker on a fund website. The ones who would rather have one operator who has done it before than five board members who have not." },
      { type: "h2", text: "What we won't do" },
      { type: "p", text: "We will not write a cheque and disappear. We will not take a board seat and only show up to vote. We will not lead a round we cannot help execute on. If a company is in a sector where we have no operating insight, no network, and no advantage to offer, we will not be in it — regardless of the upside." },
      { type: "p", text: "That last point matters. The discipline to pass on good companies where we cannot add operating value is what makes us useful in the companies we do back. We are not trying to compound the market. We are trying to compound a specific portfolio of operators who needed us in the room." },
      { type: "h2", text: "What this means if you are raising" },
      { type: "p", text: "If you want a brand name on the cap table and a partner who will pattern-match you against ten other companies in their portfolio, we are not the right partner. There are many excellent funds that will do that work, and they will do it well." },
      { type: "p", text: "If you want a partner who will sit in the room when the work is hard, build alongside you, and tell you the truth when the deck is wrong — let's talk. That is the work we have been doing for twenty years, and it is the only work we know how to do." },
    ],
  },
  {
    id: "bali-speed",
    category: "Academy",
    title: "What Bali Taught Us About Speed",
    excerpt: "Twenty-six nations in one room, eight weeks, no commute. The geography of execution is changing, and the founders who notice it first are going to compound an advantage the rest of the market will spend the next decade catching up to.",
    date: "March 5, 2026",
    readTime: "4 min read",
    author: "Julien Uhlig",
    authorRole: "Founder, EX Venture",
    image: (window.__resources && window.__resources.art3) || "assets/photos/bali-01.jpg",
    lead: "When we moved the EX Academy to Bali, the conventional read was that it was a lifestyle decision. It was not. It was a velocity decision. Three years and four cohorts in, the data has settled: founders ship faster from a single room in Ubud than they do from Lisbon, London, or the Bay.",
    body: [
      { type: "h2", text: "Geography as a speed lever" },
      { type: "p", text: "The argument against remote work was always the same: collaboration suffers, decisions slow, the chemistry that builds companies cannot be reproduced over a video call. We agree with all of it. That is why we put 26 nations in one room for eight weeks — and run the academy as a single, dense, co-located cohort with no commute and no second life pulling attention sideways." },
      { type: "p", text: "What we found surprised us. Founders ship — actual product, real revenue, signed pilots — at roughly twice the rate they shipped in distributed cohorts we ran before. The compression is not magic. It is the absence of friction." },
      { type: "h2", text: "What gets removed when you remove the city" },
      { type: "p", text: "Most cities tax founders in small ways that add up. Two-hour commutes. Restaurant booking culture. A social calendar that pretends to be a network. Cost of living calculations that creep in every week. None of these things are large alone. Together they consume the marginal hours that, in early-stage companies, are the difference between shipping and not shipping." },
      { type: "p", text: "When the only city around you is a town of 30,000 with a yoga studio and a coffee shop, those costs collapse. The hours come back. The hours go into the company." },
      { type: "h2", text: "The 26-nations dynamic" },
      { type: "p", text: "We do not screen for nationality. We screen for execution speed and a willingness to do the work. The geographic mix is downstream of that — and it has produced an unintended advantage. Founders from 26 different markets in one room get a kind of distributed sales channel by default. Every cohort produces 4–6 customer introductions across continents in the first two weeks. None of them are paid for. All of them are real." },
      { type: "p", text: "If you are building an infrastructure company, that is a meaningful head start on go-to-market." },
      { type: "h2", text: "What we look for" },
      { type: "p", text: "The academy is not a place to learn what venture capital is. It is a place to do the work alongside operators who have done it before. We want founders who already have a thesis they believe in, a willingness to be wrong about parts of it, and the discipline to ship under compressed timelines." },
      { type: "p", text: "If that describes you, the next cohort is open. If it does not, there are excellent programs elsewhere that will teach the basics. We do not." },
    ],
  },
];
